### ISSUE TITLE
unable to run beta version in chrome when close the dev-tool

### ISSUE THREAD

**Issue by iamnotstone** [donalffons/opencascade.js-examples#22]
hello ! It's very strange in my situation.
When I keep the dev-tool window of chrome closing, and the bottle example didn't work. After that, I can find these message in the console if I open (press F12) the dev-tool again:
```
Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (webpack://opencascade.js-examples/./node_modules/opencascade.js/dist/opencascade.js?:15:17694)
    at _abort (webpack://opencascade.js-examples/./node_modules/opencascade.js/dist/opencascade.js?:15:187306)
    at _Znwm (http://localhost:9000/wasm/044249d6ecbb27731cad7e42d6ecf0f4.wasm:wasm-function[9813]:0x41a075)
    at _Znam (http://localhost:9000/wasm/044249d6ecbb27731cad7e42d6ecf0f4.wasm:wasm-function[9814]:0x41a081)
    at _ZN12ChFiDS_Spine4LoadEv (<anonymous>:wasm-function[27506]:0x1bc5fe4)
    at _ZN17ChFi3d_FilBuilder3AddERK11TopoDS_Edge (<anonymous>:wasm-function[27837]:0x1c2846f)
    at _ZN24BRepFilletAPI_MakeFillet3AddEdRK11TopoDS_Edge (<anonymous>:wasm-function[28691]:0x1cf59b7)
    at _ZN10emscripten8internal13MethodInvokerIM20BlendFunc_CSCircularFvdiEvPS2_JdiEE6invokeERKS4_S5_di (<anonymous>:wasm-function[2946]:0x122b53b)
    at BRepFilletAPI_MakeFillet$Add_2 [as Add_2] (eval at new_ (webpack://opencascade.js-examples/./node_modules/opencascade.js/dist/opencascade.js?), <anonymous>:11:1)
    at makeBottle (webpack://opencascade.js-examples/./src/demos/bottle_-_basic/library.js?:146:14)
```
Or some times, I saw these message:
```
RuntimeError: memory access out of bounds
    at _ZNK12BRep_Builder5RangeERK11TopoDS_Edgeddb (<anonymous>:wasm-function[16678]:0xe2dad2)
    at _ZN16BRepLib_MakeEdge4InitERKN11opencascade6handleI10Geom_CurveEERK13TopoDS_VertexS8_dd (<anonymous>:wasm-function[18874]:0x16290b5)
    at _ZN16BRepLib_MakeEdge4InitERKN11opencascade6handleI10Geom_CurveEEdd (<anonymous>:wasm-function[18878]:0x16296bb)
    at _ZN16BRepLib_MakeEdgeC2ERKN11opencascade6handleI10Geom_CurveEE (<anonymous>:wasm-function[18902]:0x162ac2a)
    at _ZN23BRepBuilderAPI_MakeEdgeC2ERKN11opencascade6handleI10Geom_CurveEE (<anonymous>:wasm-function[19445]:0x165b62a)
    at <anonymous>:wasm-function[3213]:0x122de9f
    at _ZN10emscripten8internal7InvokerIP27BOPAlgo_AlertBadPositioningJRK12TopoDS_ShapeEE6invokeEPFS3_S6_EPS4_ (<anonymous>:wasm-function[1951]:0x1220aa2)
    at BRepBuilderAPI_MakeEdge_24.constructor_body (http://localhost:3005/occScript.worker.worker.js:10703:31)
    at BRepBuilderAPI_MakeEdge_24.<anonymous> (http://localhost:3005/occScript.worker.worker.js:10490:23)
    at new BRepBuilderAPI_MakeEdge_24 (eval at createNamedFunction (http://localhost:3005/occScript.worker.worker.js:9516:14), <anonymous>:4:34)
```
But! if I run the bottle examples and keep the dev-tools openning of chrome, then everythings just works fine.
And, in my firefox browser, everythings just works fine in any situation.

I am using a fedora 30 system and my chrome version is 89.0.4389.90 (Official Build) (64-bit)

opencascade.js version: 2.0.0-beta.2b27f74

And there is no problem when using opencascade.js 1.1.1 on my fedora.

**Comment by iamnotstone** [comment]
I think this is a memory limits problem about wasm and chrome.

**Comment by donalffons** [comment]
Yeah, I can reproduce that and I think you're right... Your first error message (`abort (undefined)`) fails at `_Znwm` which is [mangled](https://demangler.com/) for `operator new(unsigned long)`. Also, [this issue](https://github.com/donalffons/opencascade.js/issues/34) is probably related.

I wonder if adjusting [memory settings](https://emsettings.surma.technology/#INITIAL_MEMORY) (defined [here](https://github.com/donalffons/opencascade.js/blob/master/src/buildStandardModules.py#L36) in the code) or passing a custom WebAssembly.Memory during instantiation will help with this issue...

**Comment by donalffons** [comment]
Well, changing the memory settings doesn't seem to help. I just made a test with `-sINITIAL_MEMORY=1GB` with the same result...

I haven't seen this issue with custom builds that don't use WASM modules. I will try a "full" opencascade.js build with no side modules to check if that might fix the issue.

**Comment by iamnotstone** [comment]
Yes. It seems that wasm modules are somehow problematic in chrome.

**Comment by donalffons** [comment]
I just made a test locally with a "full" build and it works without issues. It also loads up so much faster than the modularized version. The resulting WASM+JS files have a size of ~45MB, i.e. much smaller than the modularized versions.

I'm wondering if its maybe a better idea to rewrite the build system for building the "full" version more efficient (faster) and drop the "module" versions of the library (or at least not ship them via NPM). The module versions currently seem to be worse in almost every aspect :frowning_face:.

**Comment by donalffons** [comment]
I just received a Chrome Update (Version 91.0.4472.101 (Official Build) (64-bit)) from my package manager. For me, the issue is now gone - the examples are working just fine, without having the devtools open.

@iamnotstone, can you verify that on your side, once you receive the update?

As a side note: It also seems like the startup-time of the WASM module version has been massively improved with this Chrome update. A while ago, I wrote [this report](https://github.com/emscripten-core/emscripten/issues/13495), in which I measured the startup time of the modularized version at ~14 seconds. When I test the same configuration now, it loads up in half that time. Also the full version loads in half the time now, by the way.

That's fantastic news! :slightly_smiling_face:

**Comment by iamnotstone** [comment]
@donalffons  chrome (Version 91.0.4472.101 (Official Build) (64-bit)) works without issue now !
